//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemGroup.Training.Pricing.Web.InventoryVoucherPricingPages
{


    public partial class Edit
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// scriptManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgScriptManager scriptManager;

        /// <summary>
        /// updMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgUpdatePanel updMain;
        protected global::SystemGroup.Web.UI.Controls.SgToolBar toolbar;



        protected global::SystemGroup.Web.UI.Controls.SgTextBox txtNumber;
        protected global::SystemGroup.Web.UI.Controls.SgTextBox txtStore;
        protected global::SystemGroup.Web.UI.Controls.SgTextBox txtStoreKeeper;
        protected global::SystemGroup.Web.UI.Controls.SgDatePicker dpDate;
        protected global::SystemGroup.Web.UI.Controls.SgTextBox txtType;
        protected global::SystemGroup.Web.UI.Controls.SgTextBox txtState;


    }
}
