//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemGroup.Training.StoreManagement.Web.Extension
{


    public partial class StoreKeeperExtension
    {

        /// <summary>
        /// updStoreKeeper control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgUpdatePanel updStoreKeeper;

        /// <summary>
        /// chkStoreKeeper control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgCheckBox chkStoreKeeper;
    }
}
