//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemGroup.Training.StoreManagement.Web.Dialog
{


    public partial class PartSelectionDialog
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        //protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// scriptManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        //protected global::SystemGroup.Web.UI.Controls.SgScriptManager scriptManager;

        /// <summary>
        /// updMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgUpdatePanel updMain;

        /// <summary>
        /// dlgPartSelection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgDialogLayout dlgPartSelection;

        /// <summary>
        /// elParts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgEntityList elParts;

        /// <summary>
        /// btnOk control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgButton btnOk;

        /// <summary>
        /// btnCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgButton btnCancel;

        /// <summary>
        /// hiddenFieldPartIdSelection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgHiddenField hiddenFieldPartIdSelection;
    }
}
